# Generated by Django 3.1.7 on 2021-03-19 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='medicalForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=25, null=True)),
                ('lastname', models.CharField(blank=True, max_length=25, null=True)),
                ('ssn', models.IntegerField()),
                ('birthdate', models.DateField()),
                ('result', models.FileField(upload_to=None)),
            ],
            options={
                'verbose_name': 'medicalform',
                'verbose_name_plural': 'medicalforms',
            },
        ),
        migrations.CreateModel(
            name='userfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=25, null=True)),
                ('lastname', models.CharField(blank=True, max_length=25, null=True)),
                ('ssn', models.IntegerField()),
                ('birthdate', models.DateField()),
                ('birthlocation', models.CharField(blank=True, max_length=25, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('DrivingLiscense', 'DrivingLiscense'), ('Passport', 'Passport'), ('SSCard', 'SSCard'), ('Violation', 'Violation')], max_length=25, null=True)),
                ('policenum', models.IntegerField()),
                ('carnum', models.IntegerField()),
                ('filenum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pishkhanapp.userfile')),
            ],
            options={
                'verbose_name': 'violation',
                'verbose_name_plural': 'violations',
            },
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofservice', models.CharField(blank=True, max_length=25, null=True)),
                ('servicedate', models.DateField()),
                ('filenum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pishkhanapp.userfile')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
        ),
        migrations.CreateModel(
            name='resultreq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regnum', models.IntegerField()),
                ('result', models.FileField(upload_to=None)),
                ('filenum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pishkhanapp.userfile')),
            ],
            options={
                'verbose_name': 'resultreq',
                'verbose_name_plural': 'resultreqs',
            },
        ),
    ]
