# Generated by Django 3.1.7 on 2021-03-23 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pishkhanapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pishkhanapp.userfile'),
        ),
    ]
