# Generated by Django 3.1.7 on 2021-03-28 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pishkhanapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files_archive',
            name='filenum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pishkhanapp.userfile'),
        ),
    ]
