# Generated by Django 3.1.7 on 2021-03-23 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pishkhanapp', '0002_auto_20210323_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalform',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='medicalform',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='medicalform',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='medicalform',
            name='ssn',
        ),
        migrations.RemoveField(
            model_name='violation',
            name='name',
        ),
    ]
