# Generated by Django 3.1.7 on 2021-03-23 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pishkhanapp', '0003_auto_20210323_0753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalform',
            old_name='user',
            new_name='filenum',
        ),
        migrations.RemoveField(
            model_name='resultreq',
            name='regnum',
        ),
    ]
