# Generated by Django 3.1.7 on 2021-03-28 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pishkhanapp', '0004_auto_20210328_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files_archive',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pishkhanapp.service'),
        ),
    ]
